import type { SoraModule, SoraSchemaEntry } from "./types";

const entry = (data: SoraSchemaEntry): SoraSchemaEntry => data;

export const SORA_SCHEMA_REGISTRY: SoraSchemaEntry[] = [
  entry({
    table: "profiles",
    module: "Core",
    purpose:
      "Stores the signed-in user's profile, timezone, display name, avatar, currency, and onboarding state.",
    keyColumns: ["id", "display_name", "timezone", "currency", "onboarded"],
    relationships: ["profiles.id -> auth.users.id"],
    userOwned: true,
    sensitive: ["display_name", "avatar_url"],
    implemented: true,
    commonQuestions: ["Siapa profil aku?", "Timezone dan currency apa yang dipakai?"],
  }),
  entry({
    table: "user_preferences",
    module: "Core",
    purpose: "Stores UI, Telegram, notification, quiet hours, and selected business preferences.",
    keyColumns: [
      "user_id",
      "theme",
      "hide_amounts",
      "selected_business_id",
      "telegram_enabled",
      "quiet_hours_start",
      "quiet_hours_end",
    ],
    relationships: [
      "user_preferences.user_id -> auth.users.id",
      "user_preferences.selected_business_id -> businesses.id",
    ],
    userOwned: true,
    sensitive: ["telegram_chat_id", "hide_amounts"],
    implemented: true,
    commonQuestions: [
      "Notifikasiku aktif?",
      "Bisnis aktif yang dipilih apa?",
      "Quiet hours jam berapa?",
    ],
  }),
  entry({
    table: "user_roles",
    module: "Core",
    purpose: "Stores user roles for authorization checks.",
    keyColumns: ["user_id", "role"],
    relationships: ["user_roles.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Role akun aku apa?"],
  }),
  entry({
    table: "tags",
    module: "Core",
    purpose: "Reusable labels for notes, files, and personal organization.",
    keyColumns: ["user_id", "name", "color", "deleted_at"],
    relationships: ["tags.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Tag apa saja yang tersedia?"],
  }),
  entry({
    table: "files",
    module: "Core",
    purpose: "Metadata for uploaded files and attachments.",
    keyColumns: ["user_id", "storage_path", "file_name", "mime_type", "category", "is_private"],
    relationships: ["files.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["storage_path", "file_name"],
    implemented: true,
    commonQuestions: ["File apa yang pernah aku simpan?"],
  }),
  entry({
    table: "notes",
    module: "Core",
    purpose: "Personal notes and general text records.",
    keyColumns: ["user_id", "title", "body", "tags", "deleted_at"],
    relationships: ["notes.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["body"],
    implemented: true,
    commonQuestions: ["Catatan terbaru apa?", "Cari catatan tentang X."],
  }),

  entry({
    table: "money_accounts",
    module: "Money",
    purpose: "Stores wallet, bank, cash, or other money accounts.",
    keyColumns: ["user_id", "name", "account_type", "initial_balance", "currency"],
    relationships: [
      "money_accounts.user_id -> auth.users.id",
      "transactions.account_id -> money_accounts.id",
    ],
    userOwned: true,
    sensitive: ["initial_balance"],
    implemented: true,
    commonQuestions: ["Akun uang apa saja?", "Saldo awal per akun berapa?"],
  }),
  entry({
    table: "money_categories",
    module: "Money",
    purpose: "Stores income and expense categories used by transactions and budgets.",
    keyColumns: ["user_id", "name", "kind", "is_required"],
    relationships: [
      "money_categories.user_id -> auth.users.id",
      "transactions.category_id -> money_categories.id",
      "budgets.category_id -> money_categories.id",
    ],
    userOwned: true,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Kategori pengeluaran apa saja?", "Budget ini kategori apa?"],
  }),
  entry({
    table: "transactions",
    module: "Money",
    purpose: "Stores income and expense records.",
    keyColumns: ["user_id", "type", "amount", "date", "category_id", "account_id", "note"],
    relationships: [
      "transactions.user_id -> auth.users.id",
      "transactions.category_id -> money_categories.id",
      "transactions.account_id -> money_accounts.id",
    ],
    userOwned: true,
    sensitive: ["amount", "note"],
    implemented: true,
    commonQuestions: [
      "Pengeluaran bulan ini berapa?",
      "Transaksi makan terakhir apa?",
      "Cashflow aman tidak?",
    ],
  }),
  entry({
    table: "budgets",
    module: "Money",
    purpose: "Envelope/category budgets with period and date range.",
    keyColumns: [
      "user_id",
      "name",
      "category_id",
      "period_type",
      "planned_amount",
      "start_date",
      "end_date",
      "status",
    ],
    relationships: [
      "budgets.user_id -> auth.users.id",
      "budgets.category_id -> money_categories.id",
    ],
    userOwned: true,
    sensitive: ["planned_amount"],
    implemented: true,
    commonQuestions: [
      "Budget bulan ini aman?",
      "Budget makan terpakai berapa?",
      "Budget mana yang lewat?",
    ],
  }),
  entry({
    table: "debts",
    module: "Money",
    purpose: "Tracks money the user owes to others.",
    keyColumns: ["user_id", "lender_name", "amount", "remaining_balance", "due_date", "status"],
    relationships: ["debts.user_id -> auth.users.id", "debt_payments.debt_id -> debts.id"],
    userOwned: true,
    sensitive: ["lender_name", "amount", "remaining_balance"],
    implemented: true,
    commonQuestions: ["Hutang aktif siapa saja?", "Hutang jatuh tempo kapan?"],
  }),
  entry({
    table: "debt_payments",
    module: "Money",
    purpose: "Payment records for debts.",
    keyColumns: ["user_id", "debt_id", "amount", "payment_date", "method"],
    relationships: ["debt_payments.debt_id -> debts.id"],
    userOwned: true,
    sensitive: ["amount", "method"],
    implemented: true,
    commonQuestions: ["Pembayaran hutang terakhir kapan?", "Sisa hutang berapa?"],
  }),
  entry({
    table: "receivables",
    module: "Money",
    purpose: "Tracks money other people owe the user.",
    keyColumns: [
      "user_id",
      "borrower_name",
      "amount",
      "remaining_amount",
      "promised_payment_date",
      "status",
    ],
    relationships: [
      "receivables.user_id -> auth.users.id",
      "receivable_payments.receivable_id -> receivables.id",
    ],
    userOwned: true,
    sensitive: ["borrower_name", "amount", "remaining_amount"],
    implemented: true,
    commonQuestions: ["Piutang siapa yang harus ditagih?", "Buat pesan tagih yang sopan."],
  }),
  entry({
    table: "receivable_payments",
    module: "Money",
    purpose: "Payment records for receivables.",
    keyColumns: ["user_id", "receivable_id", "amount", "received_date", "method"],
    relationships: ["receivable_payments.receivable_id -> receivables.id"],
    userOwned: true,
    sensitive: ["amount", "method"],
    implemented: true,
    commonQuestions: ["Siapa sudah bayar piutang?", "Piutang mana yang lunas?"],
  }),
  entry({
    table: "bills",
    module: "Money",
    purpose: "Recurring or one-off bills and due dates.",
    keyColumns: [
      "user_id",
      "name",
      "amount",
      "due_date",
      "recurrence",
      "status",
      "reminder_enabled",
    ],
    relationships: ["bills.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["amount", "name"],
    implemented: true,
    commonQuestions: ["Tagihan dekat apa saja?", "Tagihan mana yang overdue?"],
  }),
  entry({
    table: "assets",
    module: "Money",
    purpose: "Stores non-investment assets and current values.",
    keyColumns: ["user_id", "name", "asset_type", "current_value", "acquisition_date"],
    relationships: ["assets.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["current_value"],
    implemented: true,
    commonQuestions: ["Total aset berapa?", "Net worth aku berapa?"],
  }),
  entry({
    table: "investments",
    module: "Money",
    purpose: "Stores investment holdings and current prices.",
    keyColumns: [
      "user_id",
      "type",
      "ticker",
      "name",
      "quantity",
      "avg_buy_price",
      "current_price",
      "provider_symbol",
      "auto_update_enabled",
    ],
    relationships: [
      "investments.user_id -> auth.users.id",
      "investment_price_history.investment_id -> investments.id",
    ],
    userOwned: true,
    sensitive: ["quantity", "avg_buy_price", "current_price"],
    implemented: true,
    commonQuestions: [
      "Portofolio investasi untung rugi berapa?",
      "Harga investasi terakhir update kapan?",
    ],
  }),

  entry({
    table: "courses",
    module: "Activity",
    purpose: "Academic courses and class metadata.",
    keyColumns: ["user_id", "name", "code", "lecturer", "sks", "semester"],
    relationships: ["academic_tasks.course_id -> courses.id"],
    userOwned: true,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Mata kuliah aktif apa?", "Tugas per course apa?"],
  }),
  entry({
    table: "academic_tasks",
    module: "Activity",
    purpose: "Academic tasks, deadlines, priorities, and completion status.",
    keyColumns: ["user_id", "course_id", "title", "status", "priority", "due_date", "completed_at"],
    relationships: ["academic_tasks.course_id -> courses.id"],
    userOwned: true,
    sensitive: ["title", "description"],
    implemented: true,
    commonQuestions: ["Tugas paling dekat apa?", "Deadline minggu ini apa?"],
  }),
  entry({
    table: "organizations",
    module: "Activity",
    purpose: "Organizations, roles, and membership status.",
    keyColumns: ["user_id", "name", "role", "kind", "status", "started_on", "ended_on"],
    relationships: ["org_meetings.organization_id -> organizations.id"],
    userOwned: true,
    sensitive: ["role", "notes"],
    implemented: true,
    commonQuestions: ["Organisasi aktif apa?", "Peranku di organisasi apa?"],
  }),
  entry({
    table: "org_meetings",
    module: "Activity",
    purpose: "Meeting records tied to organizations.",
    keyColumns: ["user_id", "organization_id", "title", "starts_at", "ends_at", "location"],
    relationships: ["org_meetings.organization_id -> organizations.id"],
    userOwned: true,
    sensitive: ["agenda", "notes"],
    implemented: true,
    commonQuestions: ["Rapat organisasi terdekat kapan?"],
  }),
  entry({
    table: "activity_events",
    module: "Activity",
    purpose: "Internal Faza OS agenda events and optional Google Calendar sync id.",
    keyColumns: ["user_id", "title", "kind", "starts_at", "ends_at", "gcal_event_id"],
    relationships: ["activity_events.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["title", "location", "notes"],
    implemented: true,
    commonQuestions: ["Agenda hari ini apa?", "Agenda 30 hari ke depan apa?"],
  }),
  entry({
    table: "competitions",
    module: "Activity",
    purpose: "Competition registrations, deadlines, and results.",
    keyColumns: ["user_id", "name", "organizer", "status", "registration_deadline", "event_date"],
    relationships: ["competitions.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["result", "notes"],
    implemented: true,
    commonQuestions: ["Lomba aktif apa?", "Deadline lomba terdekat apa?"],
  }),
  entry({
    table: "portfolio_items",
    module: "Activity",
    purpose: "Portfolio entries for projects, achievements, and roles.",
    keyColumns: ["user_id", "title", "kind", "role", "link", "date_on"],
    relationships: ["portfolio_items.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["link", "description"],
    implemented: true,
    commonQuestions: ["Portfolio terbaru apa?", "Apa pencapaian yang bisa ditampilkan?"],
  }),

  entry({
    table: "businesses",
    module: "Business",
    purpose: "Stores each separate business or store.",
    keyColumns: ["user_id", "name", "description", "deleted_at"],
    relationships: [
      "products.business_id -> businesses.id",
      "sales.business_id -> businesses.id",
      "suppliers.business_id -> businesses.id",
    ],
    userOwned: true,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Bisnis apa saja?", "Bisnis mana yang aktif dipilih?"],
  }),
  entry({
    table: "suppliers",
    module: "Business",
    purpose: "Stores global or business-linked suppliers.",
    keyColumns: ["user_id", "business_id", "name", "contact", "notes"],
    relationships: [
      "suppliers.business_id -> businesses.id",
      "products.supplier_id -> suppliers.id",
      "supplier_business_links.supplier_id -> suppliers.id",
    ],
    userOwned: true,
    sensitive: ["contact", "notes"],
    implemented: true,
    commonQuestions: ["Supplier bisnis ini siapa?", "Supplier global apa saja?"],
  }),
  entry({
    table: "products",
    module: "Business",
    purpose: "Stores products or menu items per business with HPP, price, and stock.",
    keyColumns: ["user_id", "business_id", "name", "sku", "hpp", "price", "stock", "min_stock"],
    relationships: [
      "products.business_id -> businesses.id",
      "products.supplier_id -> suppliers.id",
      "sales.product_id -> products.id",
    ],
    userOwned: true,
    sensitive: ["hpp", "price", "stock"],
    implemented: true,
    commonQuestions: [
      "Produk bisnis ini apa?",
      "Stok produk mana yang menipis?",
      "Margin produk apa?",
    ],
  }),
  entry({
    table: "sales",
    module: "Business",
    purpose: "Stores sales records per business.",
    keyColumns: [
      "user_id",
      "business_id",
      "product_id",
      "product_name",
      "quantity",
      "unit_price",
      "unit_hpp",
      "total",
      "profit",
      "sold_at",
    ],
    relationships: ["sales.business_id -> businesses.id", "sales.product_id -> products.id"],
    userOwned: true,
    sensitive: ["total", "profit"],
    implemented: true,
    commonQuestions: ["Bisnis mana paling untung?", "Omzet bulan ini berapa?", "Top produk apa?"],
  }),

  entry({
    table: "daily_logs",
    module: "Review",
    purpose:
      "Daily journal entries with mood, energy, focus, wins, struggles, gratitude, and tomorrow focus.",
    keyColumns: ["user_id", "log_date", "mood", "energy", "focus", "wins", "struggles"],
    relationships: ["daily_logs.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["wins", "struggles", "gratitude", "tomorrow_focus"],
    implemented: true,
    commonQuestions: ["Progress journalku gimana?", "Mood 7 hari terakhir gimana?"],
  }),
  entry({
    table: "weekly_reviews",
    module: "Review",
    purpose: "Weekly reflection and area scores.",
    keyColumns: [
      "user_id",
      "week_start",
      "highlights",
      "lessons",
      "next_week_focus",
      "score_money",
      "score_health",
    ],
    relationships: ["weekly_reviews.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["highlights", "lessons", "next_week_focus"],
    implemented: true,
    commonQuestions: ["Review mingguan terakhir apa?", "Nilai health/money minggu ini?"],
  }),
  entry({
    table: "goals",
    module: "Review",
    purpose: "Goals, target dates, progress, and status.",
    keyColumns: ["user_id", "title", "area", "target_date", "progress", "status"],
    relationships: ["goals.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["notes"],
    implemented: true,
    commonQuestions: ["Goal aktif apa?", "Progress goalku berapa?"],
  }),

  entry({
    table: "workout_plans",
    module: "Health",
    purpose: "Planned workouts by date, type, duration, intensity, and status.",
    keyColumns: ["user_id", "title", "workout_date", "workout_time", "workout_type", "status"],
    relationships: ["workout_logs.workout_plan_id -> workout_plans.id"],
    userOwned: true,
    sensitive: ["notes"],
    implemented: true,
    commonQuestions: ["Workout hari ini apa?", "Workout selesai belum?"],
  }),
  entry({
    table: "workout_logs",
    module: "Health",
    purpose: "Completed workout records.",
    keyColumns: [
      "user_id",
      "workout_plan_id",
      "workout_date",
      "workout_type",
      "duration_minutes",
      "intensity",
    ],
    relationships: [
      "workout_logs.workout_plan_id -> workout_plans.id",
      "workout_sets.workout_log_id -> workout_logs.id",
    ],
    userOwned: true,
    sensitive: ["notes"],
    implemented: true,
    commonQuestions: ["Streak workout gimana?", "Workout terakhir kapan?"],
  }),
  entry({
    table: "exercise_library",
    module: "Health",
    purpose: "Exercise reference library for workout sets.",
    keyColumns: ["user_id", "name", "category", "muscle_group", "equipment"],
    relationships: ["workout_sets.exercise_id -> exercise_library.id"],
    userOwned: true,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Exercise apa saja di library?"],
  }),
  entry({
    table: "workout_sets",
    module: "Health",
    purpose: "Detailed sets for each workout log.",
    keyColumns: [
      "user_id",
      "workout_log_id",
      "exercise_id",
      "set_number",
      "reps",
      "weight",
      "duration_seconds",
    ],
    relationships: [
      "workout_sets.workout_log_id -> workout_logs.id",
      "workout_sets.exercise_id -> exercise_library.id",
    ],
    userOwned: true,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Set latihan terakhir bagaimana?"],
  }),
  entry({
    table: "body_metrics",
    module: "Health",
    purpose: "Body, sleep, hydration, and step metrics by date.",
    keyColumns: [
      "user_id",
      "metric_date",
      "weight_kg",
      "sleep_hours",
      "sleep_quality",
      "water_liters",
      "steps",
    ],
    relationships: ["body_metrics.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["weight_kg", "body_fat_percentage", "waist_cm", "sleep_hours"],
    implemented: true,
    commonQuestions: ["Berat terakhir berapa?", "Tidur rata-rata gimana?", "Air minum cukup?"],
  }),

  entry({
    table: "telegram_users",
    module: "Integrations",
    purpose: "Telegram account link state and temporary link code.",
    keyColumns: ["user_id", "chat_id", "linked_at", "link_code_expires_at"],
    relationships: ["telegram_users.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["chat_id", "link_code"],
    implemented: true,
    commonQuestions: ["Telegram sudah terhubung?", "Kapan Telegram linked?"],
  }),
  entry({
    table: "notifications",
    module: "Integrations",
    purpose: "Telegram-only scheduled notification queue/history with dedupe key.",
    keyColumns: ["user_id", "type", "channel", "dedupe_key", "status", "scheduled_at", "sent_at"],
    relationships: ["notifications.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["message", "error_message"],
    implemented: true,
    commonQuestions: ["Notifikasi terakhir apa?", "Ada notifikasi gagal?"],
  }),
  entry({
    table: "telegram_message_logs",
    module: "Integrations",
    purpose: "Inbound and outbound Telegram message log.",
    keyColumns: ["user_id", "chat_id", "direction", "message_text", "status", "created_at"],
    relationships: ["telegram_message_logs.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["chat_id", "message_text"],
    implemented: true,
    commonQuestions: ["Pesan Telegram terakhir apa?", "Ada pesan gagal terkirim?"],
  }),
  entry({
    table: "telegram_update_dedupes",
    module: "Integrations",
    purpose: "Deduplicates Telegram webhook update ids.",
    keyColumns: ["update_id", "received_at"],
    relationships: [],
    userOwned: false,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Webhook duplicate dicegah oleh tabel apa?"],
  }),
  entry({
    table: "telegram_jobs",
    module: "Integrations",
    purpose: "Queue for heavier Telegram/Sora jobs.",
    keyColumns: ["user_id", "chat_id", "job_type", "payload", "status", "attempts", "scheduled_at"],
    relationships: ["telegram_jobs.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["chat_id", "payload", "last_error"],
    implemented: true,
    commonQuestions: ["Ada job Telegram pending?", "AI request berat sedang diproses?"],
  }),
  entry({
    table: "sora_telegram_sessions",
    module: "Integrations",
    purpose: "Stores pending Sora Telegram confirmations and last intent.",
    keyColumns: [
      "user_id",
      "chat_id",
      "last_intent",
      "pending_action",
      "pending_action_expires_at",
    ],
    relationships: ["sora_telegram_sessions.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["chat_id", "pending_action"],
    implemented: true,
    commonQuestions: ["Ada aksi Sora yang menunggu konfirmasi?"],
  }),
  entry({
    table: "sora_action_logs",
    module: "Integrations",
    purpose: "Audit log of Sora parsed/executed actions.",
    keyColumns: [
      "user_id",
      "source",
      "intent",
      "confidence",
      "action_taken",
      "requires_confirmation",
      "status",
    ],
    relationships: ["sora_action_logs.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["input_text", "parsed_data", "error_message"],
    implemented: true,
    commonQuestions: ["Sora terakhir melakukan aksi apa?", "Aksi gagal apa?"],
  }),

  entry({
    table: "hpp_calculations",
    module: "Business",
    purpose: "Saved HPP calculations per business/product.",
    keyColumns: [
      "user_id",
      "business_id",
      "product_id",
      "total_cost",
      "yield_portion",
      "hpp_per_unit",
      "suggested_price",
    ],
    relationships: [
      "hpp_calculations.business_id -> businesses.id",
      "hpp_calculations.product_id -> products.id",
    ],
    userOwned: true,
    sensitive: ["total_cost", "hpp_per_unit"],
    implemented: true,
    commonQuestions: ["HPP produk ini berapa?", "Riwayat HPP terakhir apa?"],
  }),
  entry({
    table: "promo_simulations",
    module: "Business",
    purpose: "Saved promotion simulations per business/product.",
    keyColumns: [
      "user_id",
      "business_id",
      "product_id",
      "discount_percent",
      "promo_price",
      "target_units",
      "result_status",
    ],
    relationships: [
      "promo_simulations.business_id -> businesses.id",
      "promo_simulations.product_id -> products.id",
    ],
    userOwned: true,
    sensitive: ["promo_price", "expected_profit"],
    implemented: true,
    commonQuestions: ["Promo ini untung atau rugi?", "Promo aktif apa?"],
  }),
  entry({
    table: "inventory_items",
    module: "Business",
    purpose: "Inventory/stock items per business, including low stock and expiry thresholds.",
    keyColumns: [
      "user_id",
      "business_id",
      "product_id",
      "name",
      "quantity",
      "unit",
      "low_stock_threshold",
      "expires_at",
    ],
    relationships: [
      "inventory_items.business_id -> businesses.id",
      "inventory_items.product_id -> products.id",
    ],
    userOwned: true,
    sensitive: ["quantity", "unit_cost"],
    implemented: true,
    commonQuestions: ["Stok apa yang menipis?", "Bahan apa yang mau expired?"],
  }),
  entry({
    table: "inventory_movements",
    module: "Business",
    purpose: "Stock movement ledger for inventory items.",
    keyColumns: [
      "user_id",
      "business_id",
      "inventory_item_id",
      "movement_type",
      "quantity",
      "occurred_at",
    ],
    relationships: [
      "inventory_movements.inventory_item_id -> inventory_items.id",
      "inventory_movements.business_id -> businesses.id",
    ],
    userOwned: true,
    sensitive: ["quantity", "unit_cost"],
    implemented: true,
    commonQuestions: ["Kapan stok terakhir berubah?", "Restock terakhir apa?"],
  }),
  entry({
    table: "supplier_business_links",
    module: "Business",
    purpose: "Links global suppliers to one or more businesses.",
    keyColumns: ["user_id", "supplier_id", "business_id", "notes"],
    relationships: [
      "supplier_business_links.supplier_id -> suppliers.id",
      "supplier_business_links.business_id -> businesses.id",
    ],
    userOwned: true,
    sensitive: ["notes"],
    implemented: true,
    commonQuestions: ["Supplier ini dipakai bisnis mana?"],
  }),
  entry({
    table: "business_reviews",
    module: "Business",
    purpose: "Periodic business review notes and scores.",
    keyColumns: ["user_id", "business_id", "review_date", "revenue", "profit", "score", "notes"],
    relationships: ["business_reviews.business_id -> businesses.id"],
    userOwned: true,
    sensitive: ["revenue", "profit", "notes"],
    implemented: true,
    commonQuestions: ["Review bisnis terakhir gimana?", "Bisnis mana paling sehat?"],
  }),

  entry({
    table: "supplement_items",
    module: "Health",
    purpose: "Supplement inventory, dosage, frequency, stock, and threshold.",
    keyColumns: [
      "user_id",
      "name",
      "category",
      "dosage",
      "frequency",
      "stock_quantity",
      "unit",
      "low_stock_threshold",
      "price_per_unit",
    ],
    relationships: [
      "supplement_logs.supplement_id -> supplement_items.id",
      "supplement_purchases.supplement_id -> supplement_items.id",
    ],
    userOwned: true,
    sensitive: ["dosage", "notes"],
    implemented: true,
    commonQuestions: ["Suplemen apa yang stoknya rendah?", "Suplemen apa yang harus diminum?"],
  }),
  entry({
    table: "supplement_logs",
    module: "Health",
    purpose: "Supplement intake records.",
    keyColumns: ["user_id", "supplement_id", "taken_at", "quantity", "notes"],
    relationships: ["supplement_logs.supplement_id -> supplement_items.id"],
    userOwned: true,
    sensitive: ["notes"],
    implemented: true,
    commonQuestions: ["Hari ini sudah minum suplemen apa?"],
  }),
  entry({
    table: "supplement_purchases",
    module: "Health",
    purpose: "Supplement purchases linked to Money transactions.",
    keyColumns: [
      "user_id",
      "supplement_id",
      "purchase_date",
      "amount",
      "quantity",
      "store",
      "transaction_id",
    ],
    relationships: [
      "supplement_purchases.supplement_id -> supplement_items.id",
      "supplement_purchases.transaction_id -> transactions.id",
    ],
    userOwned: true,
    sensitive: ["amount", "store"],
    implemented: true,
    commonQuestions: ["Belanja suplemen bulan ini berapa?", "Beli whey terakhir kapan?"],
  }),
  entry({
    table: "recovery_logs",
    module: "Health",
    purpose: "Recovery score, soreness, stress, energy, and sleep quality logs.",
    keyColumns: [
      "user_id",
      "log_date",
      "soreness",
      "stress",
      "energy",
      "sleep_quality",
      "recovery_score",
    ],
    relationships: ["recovery_logs.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["notes"],
    implemented: true,
    commonQuestions: ["Recovery score terakhir berapa?", "Hari ini aman workout berat?"],
  }),

  entry({
    table: "investment_price_history",
    module: "Money",
    purpose: "Historical investment prices fetched from configured market data provider.",
    keyColumns: [
      "user_id",
      "investment_id",
      "ticker",
      "provider",
      "price",
      "currency",
      "fetched_at",
    ],
    relationships: ["investment_price_history.investment_id -> investments.id"],
    userOwned: true,
    sensitive: ["price", "raw"],
    implemented: true,
    commonQuestions: ["Harga investasi terakhir kapan?", "Riwayat harga ticker ini gimana?"],
  }),
  entry({
    table: "investment_price_update_logs",
    module: "Money",
    purpose: "Logs success/failure of investment price update jobs.",
    keyColumns: [
      "user_id",
      "investment_id",
      "provider",
      "status",
      "old_price",
      "new_price",
      "error_message",
      "fetched_at",
    ],
    relationships: ["investment_price_update_logs.investment_id -> investments.id"],
    userOwned: true,
    sensitive: ["old_price", "new_price", "error_message"],
    implemented: true,
    commonQuestions: ["Update harga investasi berhasil?", "Kenapa update harga gagal?"],
  }),
  entry({
    table: "google_sheets_connections",
    module: "Integrations",
    purpose: "Stores Money Google Sheets connection status.",
    keyColumns: [
      "user_id",
      "spreadsheet_id",
      "spreadsheet_url",
      "status",
      "last_sync_at",
      "last_error",
    ],
    relationships: ["google_sheets_connections.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["spreadsheet_id", "spreadsheet_url", "last_error"],
    implemented: true,
    commonQuestions: ["Google Sheets uang sudah sync?", "Spreadsheet link apa?"],
  }),
  entry({
    table: "google_sheets_sync_logs",
    module: "Integrations",
    purpose: "Per-row sync logs for Money Google Sheets mirroring.",
    keyColumns: [
      "user_id",
      "table_name",
      "sheet_name",
      "source_id",
      "status",
      "action",
      "row_number",
      "synced_at",
    ],
    relationships: ["google_sheets_sync_logs.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["error_message"],
    implemented: true,
    commonQuestions: ["Sync terakhir gagal di tabel apa?", "Kapan transaksi terakhir sync?"],
  }),

  entry({
    table: "monthly_reviews",
    module: "Review",
    purpose: "Monthly review reflections and scores.",
    keyColumns: ["user_id", "month_start", "highlights", "lessons", "next_month_focus", "score"],
    relationships: ["monthly_reviews.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: ["highlights", "lessons", "next_month_focus"],
    implemented: true,
    commonQuestions: ["Review bulanan terakhir apa?", "Progress bulan ini gimana?"],
  }),
  entry({
    table: "journal_retention_logs",
    module: "Review",
    purpose: "Audit logs for journal retention cleanup.",
    keyColumns: ["user_id", "table_name", "deleted_count", "ran_at"],
    relationships: ["journal_retention_logs.user_id -> auth.users.id"],
    userOwned: true,
    sensitive: false,
    implemented: true,
    commonQuestions: ["Journal lama dibersihkan kapan?"],
  }),
];

export function getFazaSchemaMap() {
  return SORA_SCHEMA_REGISTRY;
}

export function getFazaSchemaSummary() {
  const byModule = new Map<SoraModule, { implemented: string[]; planned: string[] }>();
  for (const item of SORA_SCHEMA_REGISTRY) {
    const group = byModule.get(item.module) ?? { implemented: [], planned: [] };
    if (item.implemented) group.implemented.push(item.table);
    else group.planned.push(item.table);
    byModule.set(item.module, group);
  }
  return Array.from(byModule.entries()).map(([module, tables]) => ({ module, ...tables }));
}

export function getModuleTables(module: SoraModule | string) {
  const m = module.toLowerCase();
  return SORA_SCHEMA_REGISTRY.filter((item) => item.module.toLowerCase() === m);
}

export function getTablePurpose(table: string) {
  return SORA_SCHEMA_REGISTRY.find((item) => item.table === table) ?? null;
}

export function isKnownTable(table: string) {
  return SORA_SCHEMA_REGISTRY.some((item) => item.table === table);
}

export function isImplementedTable(table: string) {
  return SORA_SCHEMA_REGISTRY.some((item) => item.table === table && item.implemented);
}

export const IMPLEMENTED_SORA_TABLES = SORA_SCHEMA_REGISTRY.filter((item) => item.implemented).map(
  (item) => item.table,
);
export const PLANNED_SORA_TABLES = SORA_SCHEMA_REGISTRY.filter((item) => !item.implemented).map(
  (item) => item.table,
);
