/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicCronUpdateInvestmentsRouteImport } from './routes/api/public/cron/update-investments'
import { Route as ApiPublicCronNotifyRouteImport } from './routes/api/public/cron/notify'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronUpdateInvestmentsRoute =
  ApiPublicCronUpdateInvestmentsRouteImport.update({
    id: '/api/public/cron/update-investments',
    path: '/api/public/cron/update-investments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronNotifyRoute = ApiPublicCronNotifyRouteImport.update({
  id: '/api/public/cron/notify',
  path: '/api/public/cron/notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/health': typeof AuthenticatedHealthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/more': typeof AuthenticatedMoreRoute
  '/review': typeof AuthenticatedReviewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/cron/update-investments': typeof ApiPublicCronUpdateInvestmentsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/health': typeof AuthenticatedHealthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/more': typeof AuthenticatedMoreRoute
  '/review': typeof AuthenticatedReviewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/cron/update-investments': typeof ApiPublicCronUpdateInvestmentsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/cron/update-investments': typeof ApiPublicCronUpdateInvestmentsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/assistant'
    | '/business'
    | '/health'
    | '/home'
    | '/money'
    | '/more'
    | '/review'
    | '/api/chat'
    | '/api/public/cron/notify'
    | '/api/public/cron/update-investments'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/assistant'
    | '/business'
    | '/health'
    | '/home'
    | '/money'
    | '/more'
    | '/review'
    | '/api/chat'
    | '/api/public/cron/notify'
    | '/api/public/cron/update-investments'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/assistant'
    | '/_authenticated/business'
    | '/_authenticated/health'
    | '/_authenticated/home'
    | '/_authenticated/money'
    | '/_authenticated/more'
    | '/_authenticated/review'
    | '/api/chat'
    | '/api/public/cron/notify'
    | '/api/public/cron/update-investments'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicCronNotifyRoute: typeof ApiPublicCronNotifyRoute
  ApiPublicCronUpdateInvestmentsRoute: typeof ApiPublicCronUpdateInvestmentsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/update-investments': {
      id: '/api/public/cron/update-investments'
      path: '/api/public/cron/update-investments'
      fullPath: '/api/public/cron/update-investments'
      preLoaderRoute: typeof ApiPublicCronUpdateInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notify': {
      id: '/api/public/cron/notify'
      path: '/api/public/cron/notify'
      fullPath: '/api/public/cron/notify'
      preLoaderRoute: typeof ApiPublicCronNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicCronNotifyRoute: ApiPublicCronNotifyRoute,
  ApiPublicCronUpdateInvestmentsRoute: ApiPublicCronUpdateInvestmentsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
